my first workflow

diff --git a/.github/workflows/first-example.yml b/.github/workflows/first-example.yml
--- a/.github/workflows/first-example.yml
+++ b/.github/workflows/first-example.yml
@@ -12,7 +12,7 @@ jobs:
             - name: list files
               run: ls
 
-            - name: check current directory contents
-              run: ls -la
+            - name: read file
+              run: cat README.md || echo "README.md not found"
 
         
